## peprs parameters for RM8375
---
project_id: MG001
center: NIST
RM: RM8375
ref: /pepr-data/CFSAN008157.HGAP.fasta
exp_design:
  miseq:
    - accession: SRR1555296
      plat: miseq
      vial: 0
      rep: 1
    - accession: SRR1555297
      plat: miseq
      vial: 0
      rep: 2
    - accession: SRR1555298
      plat: miseq
      vial: 1
      rep: 1
    - accession: SRR1555299
      plat: miseq
      vial: 1
      rep: 2
  pgm:
    - accession: SRR1393710
      plat: pgm
      vial: 0
      rep: 1
    - accession: SRR1393711
      plat: pgm
      vial: 1
      rep: 1
